### ISSUE TITLE
In challenge 8, Dynamic Factor cap still boost Incrementy and Quadruplier still have effect

### ISSUE THREAD

**Issue by 1e1000000** [PatcailMemer/Ordinal-Markup#13]
**Describe the bug**
I see someone beat challenge 8x2 w/o 4e27 Incrementy Upgrade (2x OP), I seem this is wrong
I also seem in challenge 8, dynamic factor cap boost incrementy multiplier isn't 1x

**To Reproduce**
Enter challenge 8

**Expected behavior**
Change row 11 of function.js from:
`  if (game.challenge <= 5.5 && (game.boostUnlock==1||game.factorShifts==7)) {` to
`  if (game.chal8 === 0 & game.challenge <= 5.5 && (game.boostUnlock==1||game.factorShifts==7)) {`

**Comment by IdleSquadron** [comment]
Still not fixed...?

**Comment by 1e1000000** [comment]
Fixed now, this will be tutorial of how to use issue

在 2020年9月8日週二 16:44，IdleSquadron <notifications@github.com> 寫道：

**Comment by 1e1000000** [comment]
I close it because there are no any reason why this exist
